Issue #31
CCC-org/keewe-backend pull request #45
Opened 2022-07-13 03:35 UTC by heoboseong7

#31 
- 닉네임 길이 제한 10자로 변경
- 닉네임 길이 0인 경우 처리
- 공백 관련 처리
  - 앞, 뒤 공백 문자 제거
  - 연속된 공백 문자들은 ' '으로 치환
  - \b 제거
- 닉네임 생성 도메인 테스트 추가

2022-07-13 20:41 UTC, Youhoseong requested changes
늦었습니다 ㅜㅜ 고생하셨어요
리뷰가 꽤나 추상적일 수 있는데요.. 변경할 부분이 없다고 판단되시면 다시 코멘트주세요

2022-07-13 20:41 UTC, Youhoseong commented on keewe-domain/src/main/java/ccc/keewedomain/domain/user/Profile.java
> +                .replaceAll("\\s+", " ");
전체적으로 Profile entity에 로직이 너무 많이 들어와있는건 아닌지 점검이 필요해보입니다.

api모듈의 service입장에선 모든 제약사항 (닉네임 길이, 닉네임 포맷)에 대한 체크가 캡슐화 돼있는 것은 좋은 구조라고 봅니다 
다만, 데이터베이스의 테이블을 표현하기도 바쁜 entity에서 비즈니스 로직에 종속되어 상황에 따라 exception을 throw하고, 
포맷을 검사하는 것이 맞는지는 모르겠어요.

entity와 밀접한 로직을 담당하기 위해 domainService개념을 적용하는 것도 좋아보여요.

정답이 없는 문제이므로 신중하게 리뷰했습니다

2022-07-13 20:41 UTC, Youhoseong commented on keewe-domain/src/test/java/ccc/keewedomain/domain/user/ProfileTest.java
>  }
Good

2022-07-14 06:40 UTC, heoboseong7 commented on keewe-domain/src/main/java/ccc/keewedomain/domain/user/Profile.java
> +                .replaceAll("\\s+", " ");
이것 저것 찾아보다가 늦었네요 ㅠ

값 검증은 서비스 레이어에서 하는게 맞는 것 같아요.
결론부터 말씀드리면 저도 DomainService 개념을 적용하는게 좋다고 생각해요.
구체적으로는
- API 서비스
  - 도메인 서비스를 조합하여 API의 기능 구현
  - 도메인의 값 또는 상태를 직접 변화(조작)시키지 못함
  - 도메인 서비스를 통해서만 조작 가능
  - DAO에 직접 접근 불가능
- 도메인 서비스
  - 자신의 도메인의 DAO에 접근 가능한 계층
  - 조회와 조작을 위한 도메인 로직들을 제공
  - 값 검증

이렇게 역할을 정해두고 Entity에는 상태 조작을 위한 간단한 메서드들만 두면 좋을 것 같아요.
혹시 피드백 있다면 말씀해주세요~~

2022-07-14 06:42 UTC, heoboseong7 commented on keewe-domain/src/main/java/ccc/keewedomain/domain/user/Profile.java
> +        final int NICKNAME_MAX_LENGTH = 10;
엔티티의 static 필드로 바꿀게요

2022-07-14 06:53 UTC, Youhoseong commented on keewe-domain/src/main/java/ccc/keewedomain/domain/user/Profile.java
> +                .replaceAll("\\s+", " ");
네 한개도 빠짐없이 전부 동의합니다~ ㅎㅎ

2022-07-14 06:54 UTC, Youhoseong commented on keewe-domain/src/main/java/ccc/keewedomain/domain/user/Profile.java
> +                .replaceAll("\\s+", " ");
바쁘시겠지만 이번 PR에서 Profile에 대해서만 말씀해주신대로 구조잡고 가시죠

2022-07-14 06:59 UTC, heoboseong7 commented on keewe-domain/src/main/java/ccc/keewedomain/domain/user/Profile.java
> +                .replaceAll("\\s+", " ");
네 한번 해볼게요 ㅎㅎ

2022-07-14 12:15 UTC, Youhoseong approved these changes

2022-07-14 12:32 UTC, merged