[Feat] 소셜 링크 등록 API (온보딩)
CCC-org/keewe-backend pull request #47
Opened 2022-07-16 12:56 UTC by heoboseong7

#32 

- 소셜 링크 등록 API 추가
- SecurityUtil 추가

2022-07-16 14:02 UTC, Youhoseong requested changes
고생했어요

2022-07-16 15:14 UTC, heoboseong7 commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
여기는 response dto가 없지만 다른 Dto들은 ~~ReqeustDto, ~~ResponseDto 이렇게 돼있어서요. 여기서 더 줄이려면 Request, Response까지만 적고 Dto를 빼는건 어떨까요?

2022-07-16 15:15 UTC, heoboseong7 commented on keewe-domain/src/main/java/ccc/keewedomain/domain/common/Link.java
> +        if(!urlObj.getHost().equals(type.getDomain())) {
getHost()가 빈 문자열을 반환하는거로 보이긴 하지만 확신하질 못하겠네요,, 제안해주신대로 바꾸는게 더 명확할 것 같아요

2022-07-16 15:35 UTC, Youhoseong commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
좋아요 다른곳도 다른 Dto도 다바꿔야겠군요 ㅋ

2022-07-16 15:36 UTC, heoboseong7 commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
이 PR에서 한번 다 갈아버리고 갈게요 ㅋㅋㅋ

2022-07-16 15:36 UTC, Youhoseong commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
아 근데 service layer 전용 dto가 나오면 ... 애매해지는데 ㅎ 일단 홀딩

2022-07-16 15:38 UTC, Youhoseong commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
아니면 위에말한부분도 정하고 가도좋구요

2022-07-16 15:48 UTC, heoboseong7 commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
서비스 레이어 dto를 api모듈의 서비스보다는 domain 모듈의 서비스에 맞춰지는게 좋다고 생각해서요. 그런데 이걸 윗부분에 적용해보려니 애매해지네요...

2022-07-16 15:55 UTC, Youhoseong commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
dto 가공하는걸 도메인서비스에서쓰든 api서비스에서 쓰든 네이밍을 어캐할거냐는 고민은 그대로긴하죠 ㅎ

api서비스에서 request Dto를 유지하는거면.. api서비스에서 LinkDto -> Link작업, SecurityUtil로 User꺼내는 작업을 하든 해야되지않을까요

api서비스에선 그냥 requestdto만 파라미터로 받아도 될거같아여

2022-07-16 16:00 UTC, Youhoseong commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
더 논의가 필요하시면 메신저로 ,,, 노트북 닫을거임ㅎ

2022-07-16 16:09 UTC, heoboseong7 commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
api의 서비스에 request dto를 바로 넘기는 방법도 좋은 것 같네요. 
그렇게 한다면 클라이언트와의 요청, 응답을 ~Request, ~Response로 하고, 도메인 서비스의 dto를 ~Dto로 하는건 어떨까요?
그러면 여기서는 SocialLinkCreateRequest, SocialLinkCreateResponse, SocialLinkDto 이렇게 나올 것 같아요

2022-07-16 16:22 UTC, Youhoseong commented on keewe-api/src/main/java/ccc/keeweapi/dto/user/SocialLinkCreateRequestDto.java
> +public class SocialLinkCreateRequestDto {
예예 그렇게가시죠

2022-07-17 05:47 UTC, Youhoseong approved these changes

2022-07-17 06:09 UTC, merged